/* Generated By:JJTree: Do not edit this line. ASTAssignUnaryStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTAssignUnaryStmt extends SimpleNode {
  public ASTAssignUnaryStmt(int id) {
    super(id);
  }

  public ASTAssignUnaryStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c020c6a122041ebc97d3f641f84465f4 (do not edit this line) */
