/* Generated By:JJTree: Do not edit this line. ASTAssignDirectStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTAssignDirectStmt extends SimpleNode {
  public ASTAssignDirectStmt(int id) {
    super(id);
  }

  public ASTAssignDirectStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=63617b55406f3e728bf6ee6068fae8b6 (do not edit this line) */
