/* Generated By:JJTree: Do not edit this line. ASTNumberRegister.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTNumberRegister extends SimpleNode {
  public ASTNumberRegister(int id) {
    super(id);
  }

  public ASTNumberRegister(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8d7f468f08cd14ac899650c9c84fe733 (do not edit this line) */
