/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTNUMBERREGISTER = 1;
  public int JJTLIVE = 2;
  public int JJTLIVENODE = 3;
  public int JJTINNODE = 4;
  public int JJTOUTNODE = 5;
  public int JJTBLOCK = 6;
  public int JJTSTMT = 7;
  public int JJTASSIGNSTMT = 8;
  public int JJTASSIGNUNARYSTMT = 9;
  public int JJTASSIGNDIRECTSTMT = 10;
  public int JJTEXPR = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTINTVALUE = 13;


  public String[] jjtNodeName = {
    "Program",
    "NumberRegister",
    "Live",
    "LiveNode",
    "InNode",
    "OutNode",
    "Block",
    "Stmt",
    "AssignStmt",
    "AssignUnaryStmt",
    "AssignDirectStmt",
    "Expr",
    "Identifier",
    "IntValue",
  };
}
/* JavaCC - OriginalChecksum=b2f8f1f17d164cad4118f5cc4f7e6743 (do not edit this line) */
